/* GUI class. The GUI has an options bar, the board and 
 * a text with the status of the game or some instructions
 */
package puzzle2dpentamino;

import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import javax.swing.*;

/**
 * @authors Sergio Vega     (43480752B)
 *          Andreas Korn    (X4890193W)
 */
public class GUI extends JFrame{
    
    private Board Board;
    private int Rows = 6, Columns = 10;
    private int Speed = 300;
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        setUpSpeedButtons();
        add(Message);                   //Adds status text
        GenerateBoard(Rows, Columns);   //Creates initial board
    }
    
    private void setUpSpeedButtons(){
        ButtonGroup g = new ButtonGroup();
        for(int i=0; i<SpeedMenu.getMenuComponentCount(); i++){
            g.add(SpeedMenu.getItem(i));
        }
        Speed3.setSelected(true);
    }
    
    /**
     * Creates a new empty board
     */
    private void GenerateBoard(int rows, int columns){
        if (Board!=null){                       //NOT initial board case
            remove(Board);                      //Deletes previous board
        }                                                
        Board = new Board(rows, columns);       //Creates a new board
        add(Board);                             //Adds the new board
        Rows = rows;  Columns = columns;        //Updates rows, columns
        Board.setSpeed(Speed);
        
        String s = "Block Squares or use Solve(Ctrl+S) to start";                   
        Message.setText(s);                                                 //Updates the status text
        Message.setBounds(0, Board.getHeight(), Board.getWidth(), 60);      //Sets it's location      
        
        int width = getInsets().right + Board.getWidth();                                                   //Frame's new width
        int height = getInsets().top + MenuBar.getHeight() + Board.getHeight() + Message.getHeight();       //Frame's new height
        setSize(width, height);                 //Sets frame's new size
        setLocationRelativeTo(null);            //Centers frame 
        setResizable(false);                    //Frame NOT resizable by the user
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Message = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        ControlMenu = new javax.swing.JMenu();
        SolveOption = new javax.swing.JMenuItem();
        ResetOption = new javax.swing.JMenuItem();
        ExitOption = new javax.swing.JMenuItem();
        SpeedMenu = new javax.swing.JMenu();
        Speed0 = new javax.swing.JRadioButtonMenuItem();
        Speed1 = new javax.swing.JRadioButtonMenuItem();
        Speed2 = new javax.swing.JRadioButtonMenuItem();
        Speed3 = new javax.swing.JRadioButtonMenuItem();
        Speed4 = new javax.swing.JRadioButtonMenuItem();
        Speed5 = new javax.swing.JRadioButtonMenuItem();
        Speed6 = new javax.swing.JRadioButtonMenuItem();
        SizeMenu = new javax.swing.JMenu();
        BoardSize0 = new javax.swing.JMenuItem();
        BoardSize1 = new javax.swing.JMenuItem();
        BoardSize2 = new javax.swing.JMenuItem();
        BoardSize3 = new javax.swing.JMenuItem();

        Message.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        Message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Puzzle2DPentominos");
        setSize(new java.awt.Dimension(1000, 1000));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        MenuBar.setSelectionModel(MenuBar.getSelectionModel());

        ControlMenu.setText("Control");

        SolveOption.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SolveOption.setText("Solve");
        SolveOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SolveOptionMouseReleased(evt);
            }
        });
        ControlMenu.add(SolveOption);

        ResetOption.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        ResetOption.setText("Reset");
        ResetOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ResetOptionMouseReleased(evt);
            }
        });
        ControlMenu.add(ResetOption);

        ExitOption.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        ExitOption.setText("Exit");
        ExitOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ExitOptionMouseReleased(evt);
            }
        });
        ControlMenu.add(ExitOption);

        MenuBar.add(ControlMenu);

        SpeedMenu.setText("Speed");

        Speed0.setText("Only solutions");
        Speed0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Speed0MouseReleased(evt);
            }
        });
        SpeedMenu.add(Speed0);

        Speed1.setText("Fastest");
        Speed1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Speed1MouseReleased(evt);
            }
        });
        SpeedMenu.add(Speed1);

        Speed2.setText("Faster");
        Speed2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Speed2MouseReleased(evt);
            }
        });
        SpeedMenu.add(Speed2);

        Speed3.setText("Normal");
        Speed3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Speed3MouseReleased(evt);
            }
        });
        SpeedMenu.add(Speed3);

        Speed4.setText("Slow");
        Speed4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Speed4MouseReleased(evt);
            }
        });
        SpeedMenu.add(Speed4);

        Speed5.setText("Slower");
        Speed5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Speed5MouseReleased(evt);
            }
        });
        SpeedMenu.add(Speed5);

        Speed6.setText("Slowest");
        Speed6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Speed6MouseReleased(evt);
            }
        });
        SpeedMenu.add(Speed6);

        MenuBar.add(SpeedMenu);

        SizeMenu.setText("Size");

        BoardSize0.setText("6 x 10");
        BoardSize0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BoardSize0MouseReleased(evt);
            }
        });
        SizeMenu.add(BoardSize0);

        BoardSize1.setText("5 x 12");
        BoardSize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BoardSize1MouseReleased(evt);
            }
        });
        SizeMenu.add(BoardSize1);

        BoardSize2.setText("4 x 15");
        BoardSize2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BoardSize2MouseReleased(evt);
            }
        });
        SizeMenu.add(BoardSize2);

        BoardSize3.setText("3 x 20");
        BoardSize3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BoardSize3MouseReleased(evt);
            }
        });
        SizeMenu.add(BoardSize3);

        MenuBar.add(SizeMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoardSize0MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoardSize0MouseReleased
        evt.consume();          //Frees memory
        GenerateBoard(6,10);    //New (6x10) board
    }//GEN-LAST:event_BoardSize0MouseReleased

    private void BoardSize1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoardSize1MouseReleased
        evt.consume();          //Frees memory 
        GenerateBoard(5,12);    //New (5x12) board
    }//GEN-LAST:event_BoardSize1MouseReleased

    private void BoardSize2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoardSize2MouseReleased
        evt.consume();          //Frees memory 
        GenerateBoard(4,15);    //New (4x15) board
    }//GEN-LAST:event_BoardSize2MouseReleased

    private void BoardSize3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoardSize3MouseReleased
        evt.consume();          //Frees memory 
        GenerateBoard(3,20);    //New (3x20) board
    }//GEN-LAST:event_BoardSize3MouseReleased

    private void ExitOptionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitOptionMouseReleased
        evt.consume();      //Frees memory 
        System.exit(0);     //Exits the program
    }//GEN-LAST:event_ExitOptionMouseReleased

    private void ResetOptionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetOptionMouseReleased
        evt.consume();                  //Frees memory 
        GenerateBoard(Rows, Columns);   //New board with the previous one rows and columns
    }//GEN-LAST:event_ResetOptionMouseReleased

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        if(!Board.isSolving()){
            if ((evt.getY() > getInsets().top + MenuBar.getHeight())                //MouseEvent happened inside board
                    && (evt.getY() < getInsets().top + MenuBar.getHeight() + Board.getHeight())){    

                int x = evt.getX() - getInsets().right;                             //Fixed coordinates
                int y = evt.getY() + getInsets().bottom - (2*getInsets().top);;     //Fixed coordinates
                evt.consume();                      //Frees memory

                Board.ChangeSquareStatus(x, y);     //Updates square's status and color
            }
            repaint();                          //Updates the GUI with the new square's color
        }
    }//GEN-LAST:event_formMouseReleased

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        int key = evt.getKeyCode();
        if (evt.isControlDown() && (key == KeyEvent.VK_E)){
            evt.consume();
            System.exit(0);
        }
        else if (evt.isControlDown() && (key == KeyEvent.VK_R)){
            evt.consume();
            GenerateBoard(Rows, Columns);
        }
        else if (evt.isControlDown() && (key == KeyEvent.VK_S)){
            evt.consume();
            new Thread(() -> {
                solve();     //Inicia el puzzle
            }).start();
        }
    }//GEN-LAST:event_formKeyReleased

    private void SolveOptionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SolveOptionMouseReleased
        evt.consume();
            new Thread(() -> {
                solve();     //Inicia el puzzle
            }).start();
    }//GEN-LAST:event_SolveOptionMouseReleased

    private void Speed0MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Speed0MouseReleased
        evt.consume();
        setSpeed(0);
    }//GEN-LAST:event_Speed0MouseReleased

    private void Speed1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Speed1MouseReleased
        evt.consume();
        setSpeed(100);
    }//GEN-LAST:event_Speed1MouseReleased

    private void Speed2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Speed2MouseReleased
        evt.consume();
        setSpeed(200);
    }//GEN-LAST:event_Speed2MouseReleased

    private void Speed3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Speed3MouseReleased
        evt.consume();
        setSpeed(300);
    }//GEN-LAST:event_Speed3MouseReleased

    private void Speed4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Speed4MouseReleased
        evt.consume();
        setSpeed(500);
    }//GEN-LAST:event_Speed4MouseReleased

    private void Speed5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Speed5MouseReleased
        evt.consume();
        setSpeed(700);
    }//GEN-LAST:event_Speed5MouseReleased

    private void Speed6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Speed6MouseReleased
        evt.consume();
        setSpeed(1000);
    }//GEN-LAST:event_Speed6MouseReleased

    private void setSpeed(int miliseconds){
        Speed = miliseconds;
        Board.setSpeed(miliseconds);
    }
    
    private void solve(){
        if(!Board.isSolving()){
            Message.setText("Solving...");
            Board.setSolving(true);
            Board.Solve(this, 0, new boolean[12]);
            Message.setText("Solved");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);     //Inicia el puzzle
            }
        });
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BoardSize0;
    private javax.swing.JMenuItem BoardSize1;
    private javax.swing.JMenuItem BoardSize2;
    private javax.swing.JMenuItem BoardSize3;
    private javax.swing.JMenu ControlMenu;
    private javax.swing.JMenuItem ExitOption;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JLabel Message;
    private javax.swing.JMenuItem ResetOption;
    private javax.swing.JMenu SizeMenu;
    private javax.swing.JMenuItem SolveOption;
    private javax.swing.JRadioButtonMenuItem Speed0;
    private javax.swing.JRadioButtonMenuItem Speed1;
    private javax.swing.JRadioButtonMenuItem Speed2;
    private javax.swing.JRadioButtonMenuItem Speed3;
    private javax.swing.JRadioButtonMenuItem Speed4;
    private javax.swing.JRadioButtonMenuItem Speed5;
    private javax.swing.JRadioButtonMenuItem Speed6;
    private javax.swing.JMenu SpeedMenu;
    // End of variables declaration//GEN-END:variables

}
